name: search_13
description: A Dart package providing various search algorithms including Binary Search, Linear Search, and Jump Search.
version: 1.0.0
repository: https://github.com/Iskandarrcode/package_13_search

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
